<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\BuildingBlocks\BuildingBlocks\BuildingBlocks.csproj" />
    <ProjectReference Include="..\Providers.Domain\Providers.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.10" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Drivers\Commands\" />
    <Folder Include="Drivers\Queries\" />
    <Folder Include="Vehicles\Commands\" />
    <Folder Include="Vehicles\Queries\" />
  </ItemGroup>

</Project>
