version: '3.4'

services:
  providersdb:
    image: mcr.microsoft.com/mssql/server

  ordersdb:
    image: mcr.microsoft.com/mssql/server

  messagebroker:
    image: rabbitmq:management

  redis:
    image: redis

  providers.api:
    image: ${DOCKER_REGISTRY-}providersapi
    build:
      context: .
      dockerfile: Services/Providers/Providers.API/Dockerfile


  yarpapigateway:
    image: ${DOCKER_REGISTRY-}yarpapigateway
    build:
      context: .
      dockerfile: ApiGateways/YarpApiGateway/Dockerfile


  orders.api:
    image: ${DOCKER_REGISTRY-}ordersapi
    build:
      context: .
      dockerfile: Services/Orders/Orders.API/Dockerfile

